sudo: required
services:
    - docker

before_install:
    - docker build -t docker-test123/docker-react -f Dockerfile.dev .

script:
    - docker run docker-test123/docker-react npm run test -- --coverage